spring:
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

mybatis:
  configuration:
    map-underscore-to-camelCase: true
    cache-enabled: false
    use-generated-keys: true
    default-statement-timeout: 10
  mapper-locations: "classpath*:mappers/**/*.xml"

okhttp3:
  readTimeout: 5
  connectTimeout: 5
  maxIdleConnections: 1
  keepAliveDuration: 1